### ISSUE TITLE
Create a sub-system for organizing/linking noise modules

### ISSUE THREAD

**Issue by nnarain** [nnarain/mapgen2#2]
This will be the system that creates and links noise modules together. Noise modules do not refer directly to libnoise modules. A noise module can refer to individual libnoise modules or other noise modules linked together.

For example:

```yaml
Module 1:
  sources:
    - noise 1
    - noise 2:
      source: noise 1
  output: noise 2

Module 2:
  sources:
    - noise 1
      source: Module 1 
```

Something like that.
